import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { useState, useEffect } from "react";
import { api } from "~/utils/api";
import Up from "~/animations/up";




import DashboardScreen from "~/screens/DashboardScreen";
import ProfileViewScreen from "~/screens/ProfileViewScreen";
import Loading from "~/components/test/Loading";

// import data from './clenovia.json';

export default function pravidla() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="head w-full">
        <div className="top-bg">
          
          </div>
          <div className="inner text-center">
          <h1 className="text-5xl font-extrabold">Pravidla</h1>
          <p className="my-4 text-xl font-bold desc">Základní pravidla serveru, kterými se řídí hráči</p>
            </div>
    {/* // ak je event tak daj true */}


    </div>
        hello
    </>
  );
}


