import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { useState, useEffect } from "react";
import { api } from "~/utils/api";
import Up from "~/animations/up";




import DashboardScreen from "~/screens/DashboardScreen";
import ProfileViewScreen from "~/screens/ProfileViewScreen";
import Loading from "~/components/test/Loading";

// import data from './clenovia.json';

export default function pravidla() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="head">
        <div className="top-bg">
          </div>
          
    {/* // ak je event tak daj true */}

    <div className="inner home-grid ">
            <img className="logo" src="/Hardmode-logo.png"/>
        <div>
          <h1 className="text-8xl font-extrabold title">Enchant</h1>
          <a href="/form" className="">
            <button className="prihlaska-btn">Přihláška</button>
            </a>
            </div>
    </div>

        </div>
        hello
    </>
  );
}


