import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { useState, useEffect } from "react";
import { api } from "~/utils/api";
import Up from "~/animations/up";




import DashboardScreen from "~/screens/DashboardScreen";
import ProfileViewScreen from "~/screens/ProfileViewScreen";
import Loading from "~/components/test/Loading";

// import data from './clenovia.json';

export default function clenovia() {
    const [data,setData]=useState([]);
    const [loading, setLoading] = useState(false);
    const getData=()=>{
      fetch('clenovia.json'
      ,{
        headers : { 
          'Content-Type': 'application/json',
          'Accept': 'application/json'
         }
      }
      )

        .then(function(response){
            setLoading(true);
          return response.json();
        })
        .then(function(myJson) {
          setData(myJson)
        });
    }
    useEffect(()=>{
      getData()
      setLoading(false);
    },[])
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="head">
        <div className="top-bg">
          </div>
          
    {/* // ak je event tak daj true */}

    <div className="inner home-grid ">
            <img className="logo" src="/Hardmode-logo.png"/>
        <div>
          <h1 className="text-8xl font-extrabold title">Enchant</h1>
          <a href="/form" className="">
            <button className="prihlaska-btn">Přihláška</button>
            </a>
            </div>
    </div>
        </div>
        {loading ? 
        <div className="page py-12 grid lg:grid-cols-3 gap-4 max-w-screen-xl mx-auto md:grid-cols-2 sm:grid-cols-1 px-12">

            {data.map((item) => 
            <div className=" bg-slate-600 grid grid-cols-2 p-3 rounded-md shadow">
            {/* <img src={`https://cravatar.eu/avatar/${Chleba_}/64.png`} /> */}
            <img className="rounded-md shadow" loading="lazy" src="https://cravatar.eu/avatar/Chleba_/64.png" />
            <div className="text-right">
            <h1 className="text-2xl font-bold">{item.nick}</h1>
            <h1 className="text-xl text-slate-300">{item.date}</h1>
            </div>
            </div>
            )}
    </div>
                :
                <Loading/>}
    </>
  );
}


