import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import { getServerAuthSession } from "~/server/auth";

const Dashboard: NextPage = () => {
  const session = useSession();
  const secret = api.protected.getSecretMessage.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className="mt-40 radius flex flex-col items-center gap-2 border p-4">
          <h1 className="text-lg">Dashboard - Protected</h1>
          <p>{JSON.stringify(session)}</p>
          <p>{secret.data ? secret.data : "Loading tRPC query..."}</p>
          <button
            onClick={() => signOut()}
            className="rounded border py-1 px-4"
          >
            Logout
          </button>
        </div>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getServerAuthSession({
    req: context.req,
    res: context.res,
  });

  if (!session) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }

  return { props: {} };
};

export default Dashboard;