import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";

import { getServerAuthSession } from "~/server/auth";
import RegisterForm from "~/components/RegisterForm";
import Header from "~/components/header";
import Footer from "~/components/footer";

const Register: NextPage = () => {
  return (
    <>
      <Head>
        <title>Magyar</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
        <RegisterForm />
        <Footer />
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getServerAuthSession({
    req: context.req,
    res: context.res,
  });

  if (session) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }

  return { props: {} };
};

export default Register;